spring:
  application:
    name: screen-match

  # DB configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST}/series_db_2
    username: ${DB_USER_POST}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
    hibernate:
      ddl-auto: update